server:
  port: 0 #random

spring:
  application:
    name: app-kafka-stream-3
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ${spring.application.name}
      properties:
        default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler